version: '3'

services:
  httpd:
    build: 
      context: bin/httpd
    container_name: 'poolcp.alimerka.con-voz-de-mujer_httpd'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT-31514}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT-31515}:443"
    links: 
      - mysql
    volumes:
      - ../composer.json:/var/www/composer.json
      - ../auth.json:/var/www/auth.json
      - ../composer.lock:/var/www/composer.lock
      - ../app:/var/www/app
      - ../vendor:/var/www/vendor
      - ../phpunit.xml:/var/www/phpunit.xml
      - ../tests:/var/www/tests
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MYSQL_SERVER: ${MYSQL_SERVER-poolcp.alimerka.con-voz-de-mujer_mysql}
      MYSQL_USER: ${MYSQL_USER-mysqlu}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-mysqlp}
      MYSQL_DATABASE: ${MYSQL_DATABASE-poolcp.alimerka.con-voz-de-mujer}
      MYSQL_CONNECTION_FROM: ${MYSQL_CONNECTION_FROM-poolcp.alimerka.con-voz-de-mujer_httpd}
      GESTYMVC_DEBUG: ${GESTYMVC_DEBUG-false}
      GESTYMVC_ENVIRONMENT: ${GESTYMVC_ENVIRONMENT-default}
      AMAZON_S3_SECRET: ${AMAZON_S3_SECRET}
  mysql:
    build:
      context: './bin/mysql'
    container_name: 'poolcp.alimerka.con-voz-de-mujer_mysql'
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE-poolcp.alimerka.con-voz-de-mujer}
      MYSQL_USER: ${MYSQL_USER-mysqlu}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-mysqlp}
  cronjobber:
    image: docker:edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: poolcp.alimerka.con-voz-de-mujer_cronjobber
    command: >
      sh -c "
      echo '* * * * * docker exec poolcp.alimerka.con-voz-de-mujer_httpd php "/var/www/app/public/index.php" --document_root="/var/www/app/public" --url="/cron/worker/" | grep MSG' > /etc/crontabs/root
      && crond -f"