AdminUsers: User
Seo: CanonicalUrl
Texts: LayoutText
"*": True
"!":
  - AclCacheUserPermission
  - AclProfilePermission
  - ContentType
  - DbMigration
  - Log
  - QueuedTask
  - UserPasswordHistory
  - UserTfaToken
  - Webhook
